In [1]:
from core.graph import *

In [2]:
G = PathGraph('TestGraph', directed=0)

In [3]:
# create a bunch of nodes
nodes = [Node(G) for i in range(12)]

In [4]:
# create a bunch of edges
G.node(1).link(2)
G.node(1).link(7)
G.node(1).link(8)
G.node(2).link(3)
G.node(2).link(6)
G.node(3).link(4)
G.node(3).link(5)
G.node(5).link(6)
G.node(6).link(9)
G.node(8).link(9)
G.node(8).link(12)
G.node(9).link(10)
G.node(9).link(11)

```mermaid
flowchart LR
    id_1((1))
    id_2((2))
    id_3((3))
    id_4((4))
    id_5((5))
    id_6((6))
    id_7((7))
    id_8((8))
    id_9((9))
    id_10((10))
    id_11((11))
    id_12((12))
    id_1 --- id_2
    id_1 --- id_7
    id_1 --- id_8
    id_2 --- id_3
    id_2 --- id_6
    id_3 --- id_4
    id_3 --- id_5
    id_5 --- id_6
    id_6 --- id_9
    id_8 --- id_9
    id_8 --- id_12
    id_9 --- id_10
    id_9 --- id_11
```

In [5]:
a = [3,1,5,8,3,0]

In [6]:
set(a)

{0, 1, 3, 5, 8}

In [7]:
paths = G.find_all_paths(5, 9, verbose=1)

step 0) Current Sequence: [5]
	5 is a new branch
	go to 3 ...
step 1) Current Sequence: [5, 3]
	3 is a new branch
	go to 2 ...
step 2) Current Sequence: [5, 3, 2]
	2 is a new branch
	go to 1 ...
step 3) Current Sequence: [5, 3, 2, 1]
	1 is a new branch
	go to 8 ...
step 4) Current Sequence: [5, 3, 2, 1, 8]
	8 is a new branch
	go to 12 ...
step 5) Current Sequence: [5, 3, 2, 1, 8, 12]
	12 is a dead-end, return back to 8
step 6) Current Sequence: [5, 3, 2, 1, 8]
	go to 9 ...
step 7) Current Sequence: [5, 3, 2, 1, 8, 9]
found sequence: [5, 3, 2, 1, 8, 9]
step 8) Current Sequence: [5, 3, 2, 1, 8]
	All exits searched at 8, prune branch ...
	go back to branch 1 ...
step 9) Current Sequence: [5, 3, 2, 1]
	go to 7 ...
step 10) Current Sequence: [5, 3, 2, 1, 7]
	7 is a dead-end, return back to 1
step 11) Current Sequence: [5, 3, 2, 1]
	All exits searched at 1, prune branch ...
	go back to branch 2 ...
step 12) Current Sequence: [5, 3, 2]
	go to 6 ...
step 13) Current Sequence: [5, 3, 2, 6]
	6 i

In [8]:
for p in paths:
    p.show()

5 -> 6 -> 2 -> 1 -> 8 -> 9
5 -> 3 -> 2 -> 1 -> 8 -> 9
5 -> 6 -> 9
5 -> 3 -> 2 -> 6 -> 9


In [9]:
A = G.adjacency_matrix()

In [10]:
A


array([[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [11]:
A @ A

array([[3, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 3, 0, 1, 2, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 3, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 2, 0, 0, 3, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 3, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 4, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

In [12]:
np.where(A[4] > 0)

(array([2, 5], dtype=int64),)

In [13]:
G.distance(5, 9)

2

In [14]:
G.spectrum()

array([ 2.60816180e+00, -2.41583960e+00, -2.19270475e+00,  1.80871371e+00,
        1.45143081e+00, -1.29141127e+00,  7.38047015e-01,  4.89927593e-01,
       -6.57650579e-01, -5.38674718e-01, -6.36764040e-17, -1.23259516e-32])

In [15]:
G.shortest_path_slow(5, 9).show()

5 -> 6 -> 9


In [16]:
G.shortest_path_slow(5, 9, respect_edge_length=True).show()

5 -> 6 -> 9


In [17]:
G.shortest_path(5, 9).show()

5 -> 6 -> 9


In [ ]:
# benchmark shortest path algos
from time import perf_counter_ns

start = perf_counter_ns()
G.shortest_path(5, 9)
delta = perf_counter_ns() - start
print(f'Shortest Path Algo: {delta}ns')

start = perf_counter_ns()
G.shortest_path_slow(5, 9)
delta = perf_counter_ns() - start
print(f'Shortest Path Slow Algo: {delta}ns')

In [18]:
for i in range(5-1, 0, -1):
    print(i)

4
3
2
1


In [19]:
issubclass(type(G), GraphLike)

True

In [20]:
G.adjacency_matrix()

array([[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [21]:
a = AdvancedGraph()

for i in range(10):
    a.add_node(i)

a.node(0).link(9)
a.node(9).link(2)
a.node(5).link(3)
a.node(1).link(6)
a.node(6).link(8)

In [22]:
print('Advanced Graph Nodes:', a.node_space)
ccs = a.split_into_components()
for cc in ccs:
    print(f'Component ({cc.component_id}):', cc.node_space)

Advanced Graph Nodes: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
Component (0): {0, 9, 2}
Component (1): {8, 1, 6}
Component (2): {3, 5}
Component (3): {4}
Component (4): {7}


In [23]:
a.components

{0: <core.graph.ConnectedComponent at 0x21626082250>,
 1: <core.graph.ConnectedComponent at 0x21626092090>,
 2: <core.graph.ConnectedComponent at 0x21626092250>,
 3: <core.graph.ConnectedComponent at 0x216260923d0>,
 4: <core.graph.ConnectedComponent at 0x21626092550>}

In [24]:
a.adjacency_matrix()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
b = a * a
b.adjacency_matrix()

array([[1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [26]:
b.name

'Graph_01 x Graph_01'